# CaaS Working CI/CD
stages:
  - build_flask
  - deploy

variables:
  CONTAINER_IMAGE: $GITLAB_REGISTRY_URL/$GITLAB_REGISTRY_NAMESPACE/ensembl-2020-server:${CI_COMMIT_SHORT_SHA}
  KUBECONFIG: /etc/deploy/config

Build e!-Server:
  stage: build_flask

  image: docker

  services:
    - docker:dind

  script:
  - docker build -t ${CONTAINER_IMAGE} --no-cache .
  - docker images
  - echo "$GITLAB_REGISTRY_TOKEN" | docker login -u "$GITLAB_REGISTRY_USER" --password-stdin https://"$GITLAB_REGISTRY_URL"
  - docker push ${CONTAINER_IMAGE}
  - docker rmi ${CONTAINER_IMAGE}
  - docker logout $GITLAB_REGISTRY_URL

  only:
  - cicd-test

# Deploy Stage 
Staging:
  stage: deploy
  image: alpine
  only:
  - cicd-test
  before_script:
  - mkdir -p /etc/deploy
  - echo ${EMBASSY_KUBECONFIG} | base64 -d > ${KUBECONFIG}
  script:
  - apk update && apk add --no-cache curl git
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - mv ./kubectl /usr/local/bin/kubectl
  - git clone https://gitlab.ebi.ac.uk/kamal/ensembl-client-caas-deploy.git
  - cd ensembl-client-caas-deploy
  - git checkout embassy_migration
  - sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" ensembl-client-caas-deploy/ett_server_cicd_test_deployment.yaml
  - sed -i "s/<DEPLOYMNET_ENV>/staging/g" ensembl-client-caas-deploy/ett_server_cicd_test_deployment.yaml
  - sed -i "s/<DEPLOYMNET_ENV>/staging/g" ensembl-client-caas-deploy/ett_server_cicd_test_node.yaml
  - kubectl config view
  - kubectl config use-context ens-stage-ctx
  - kubectl apply -f ensembl-client-caas-deploy/ett_server_cicd_test_node.yaml
  - kubectl apply -f ensembl-client-caas-deploy/ett_server_cicd_test_deployment.yaml

#Live:
#  stage: deploy
#  image: alpine
#  only:
#  - cicd-test
#  before_script:
#  - mkdir -p /etc/deploy
#  - echo ${KUBE_CONFIG} | base64 -d > ${KUBECONFIG}
#  script:
#  - apk update && apk add --no-cache curl git
#  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
#  - chmod +x ./kubectl
#  - mv ./kubectl /usr/local/bin/kubectl
#  - git clone https://gitlab.ebi.ac.uk/kamal/ensembl-client-caas-deploy.git
#  - sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" ensembl-client-caas-deploy/ett_server_cicd_test_deployment.yaml
#  - sed -i "s/<DEPLOYMNET_ENV>/prod/g" ensembl-client-caas-deploy/ett_server_cicd_test_deployment.yaml
#  - sed -i "s/<DEPLOYMNET_ENV>/prod/g" ensembl-client-caas-deploy/ett_server_cicd_test_node.yaml
#  - kubectl config use-context ucp_hh-ucp.caas.ebi.ac.uk:6443_kamal
#  - kubectl apply -f ensembl-client-caas-deploy/ett_server_cicd_test_node.yaml
#  - kubectl apply -f ensembl-client-caas-deploy/ett_server_cicd_test_deployment.yaml
#  when: manual