# CI/CD Pipeline
# dev branch -> staging
# master branch -> internal
# master branch -> live

# Define stages for the CI/CD pipeline
stages:
  - build_flask
  - deploy

variables:
  CONTAINER_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
  DOCKER_TLS_CERTDIR: ""

# Template to build to docker image
.build:
  stage: build_flask
  image: docker
  services:
    - docker:dind

  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

  script:
  - docker build -t ${CONTAINER_IMAGE} --no-cache .
  - docker push ${CONTAINER_IMAGE}
  - docker rmi ${CONTAINER_IMAGE}
  - docker logout $CI_REGISTRY

# Template to deploy to WP k8s cluster
.deploy-wp:
  stage: deploy
  image: dockerhub.ebi.ac.uk/kamal/deploy-tools:0.1

  script:
  - git clone https://gitlab.ebi.ac.uk/ensembl-web/ensembl-k8s-manifests.git
  - git -C ensembl-k8s-manifests/ checkout wp-k8s
  - sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" ensembl-k8s-manifests/ensembl_server_deployment.yaml
  - sed -i "s#<NFS_SERVER>#${NFS_SERVER}#g" ensembl-k8s-manifests/ensembl_server_deployment.yaml
  - sed -i "s#<NFS_PATH>#${NFS_PATH}#g" ensembl-k8s-manifests/ensembl_server_deployment.yaml
  - kubectl apply -f ensembl-k8s-manifests/ensembl_server_deployment.yaml

# Template to deploy review apps to WP k8s cluster
.deploy-wp-review:
  stage: deploy
  image: dockerhub.ebi.ac.uk/kamal/deploy-tools:0.1

  script:
  - git clone https://gitlab.ebi.ac.uk/ensembl-web/ensembl-k8s-manifests.git
  - git -C ensembl-k8s-manifests/ checkout wp-k8s-review
  - sed -i "s#<DOCKER_IMAGE>#${CONTAINER_IMAGE}#g" ensembl-k8s-manifests/ensembl_server_deployment.yaml
  - sed -i "s#<DEPLOYMENT_ENV>#${CI_COMMIT_REF_SLUG}#g" ensembl-k8s-manifests/ensembl_server_deployment.yaml
  - sed -i "s#<NFS_SERVER>#${NFS_SERVER}#g" ensembl-k8s-manifests/ensembl_server_deployment.yaml
  - sed -i "s#<NFS_PATH>#${NFS_PATH}#g" ensembl-k8s-manifests/ensembl_server_deployment.yaml
  - kubectl apply -f ensembl-k8s-manifests/ensembl_server_deployment.yaml

# Build docker image for live/internal/stage environment
Docker:IMG:
  extends: .build
  only:
  - dev
  - master

# Build docker image for feature_branch dev environment
Docker:review:
  extends: .build
  variables:
    CONTAINER_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}-${CI_COMMIT_REF_SLUG}

  except:
  - dev
  - master
  - /^nodeploy\/.*$/

# Deploy staging to WP-HX cluster
Staging:WP-HX:
  extends: .deploy-wp
  variables:
    NFS_SERVER: hx-isi-srv-vlan157.ebi.ac.uk
    NFS_PATH: /ifs/public-r/ro/enswbsites
  environment:
    name : wp-hx-staging
  only:
  - dev

# Deploy staging to WP-HH cluster
Staging:WP-HH:
  extends: .deploy-wp
  variables:
    NFS_SERVER: hh-isi-srv-vlan1493.ebi.ac.uk
    NFS_PATH: /ifs/public/ro/enswbsites
  environment:
    name : wp-hh-staging
  only:
  - dev

# Deploy staging to WP-HX cluster
Live:WP-HX:
  extends: .deploy-wp
  variables:
    NFS_SERVER: hx-isi-srv-vlan157.ebi.ac.uk
    NFS_PATH: /ifs/public-r/ro/enswbsites
  environment:
    name : wp-hx-live
  only:
  - master

# Deploy staging to WP-HX cluster
Live:WP-HH:
  extends: .deploy-wp
  variables:
    NFS_SERVER: hh-isi-srv-vlan1493.ebi.ac.uk
    NFS_PATH: /ifs/public/ro/enswbsites
  environment:
    name : wp-hh-live
  only:
  - master

# Deploy internal to WP-HX cluster
Internal:WP-HX:
  extends: .deploy-wp
  variables:
    NFS_SERVER: hx-isi-srv-vlan157.ebi.ac.uk
    NFS_PATH: /ifs/public-r/ro/enswbsites
  environment:
    name : wp-hx-internal
  only:
  - dev

# Deploy internal to WP-HH cluster
Internal:WP-HH:
  extends: .deploy-wp
  variables:
    NFS_SERVER: hh-isi-srv-vlan1493.ebi.ac.uk
    NFS_PATH: /ifs/public/ro/enswbsites
  environment:
    name : wp-hh-internal
  only:
  - dev

# Deploy dev to WP-HX cluster
Dev:WP-HX:
  extends: .deploy-wp
  variables:
    NFS_SERVER: hx-isi-srv-vlan157.ebi.ac.uk
    NFS_PATH: /ifs/public-r/ro/enswbsites
  environment:
    name : wp-hx-dev
  only:
  - dev

# Deploy Review app to WP-HX cluster
Review:WP-HX:
  extends: .deploy-wp-review
  variables:
    CONTAINER_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}-${CI_COMMIT_REF_SLUG}
    NFS_SERVER: hx-isi-srv-vlan157.ebi.ac.uk
    NFS_PATH: /ifs/public-r/ro/enswbsites
  environment:
    name : wp-hx-dev
  except:
  - dev
  - master
  - /^nodeploy\/.*$/
