openapi: 3.0.1
info:
  title: Ensembl - 2020
  description: The genome-browser API for 2020.ensembl.org
  contact:
    email: kamal@ebi.ac.uk
  version: 0.0.1
servers:
- url: https://2020.ensembl.org
- url: http://2020.ensembl.org
tags:
- name: api
  description: genome-browser API
paths:
  /browser/config:
    get:
      tags:
      - api
      summary: Broswer configuration
      description: Returns a browser configuration
      responses:
        200:
          description: Get genome-browser configuration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrowserConfig'
      security:
      - api_key: []
  /browser/config/{version}:
    get:
      tags:
      - api
      summary: Versioned browser configuration
      description: retruns sepcific version of browser configuration
      parameters:
      - name: version
        in: path
        required: true
        schema:
          type: integer
          default: 1
      responses:
        200:
          description: Get genome browser configuration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrowserConfig'
      security:
      - api_key: []
  /browser/data/1/{spec}:
    get:
      tags:
      - api
      summary: Versioned browser configuration
      description: retruns sepcific version of browser configuration
      parameters:
      - name: spec
        in: path
        required: true
        schema:
          type: integer
          default: 1
      responses:
        200:
          description: Get genome browser configuration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrowserConfig'
      security:
      - api_key: []
  /browser/data/3/{spec}:
    get:
      tags:
      - api
      summary: Versioned browser configuration
      description: retruns sepcific version of browser configuration
      parameters:
      - name: spec
        in: path
        required: true
        schema:
          type: string
          default: triticum_aestivum_GCA_900519105_1:gene:TraesCS3D02G273600~triticum_aestivum_GCA_900519105_1:chr3D:ff=R7590759
      responses:
        200:
          description: Get genome browser configuration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrowserData'
              examples: 
                browser-data-success:
                  $ref: '#/components/examples/browser-data-3-spec-success'
      security:
      - api_key: []
  /browser/locale/{id}:
    get:
      tags:
      - api
      summary: Versioned browser configuration
      description: retruns sepcific version of browser configuration
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          default: homo_sapiens_GCA_000001405_14:gene:ENSG00000139618
      responses:
        200:
          description: Get genome browser configuration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrowserLocale'
              examples: 
                browser-data-success:
                  $ref: '#/components/examples/browser-locale-success'
      security:
      - api_key: []
components:
  schemas:
    BrowserConfig:
      type: object
      properties:
        api: 
          type: object
        assets: 
          type: object
        bytcodes: 
          type: object
        sticks: 
          type: object
        tracks:
          type: object
        data-url:
          type: string
          example: './data/1'
        debug-url:
          type: string
          example: './data/1'
        endpoints:
          type: string
          example: './data/1'
        jumper-url:
          type: string
          example: "./locale"
    BrowserData:
      type: object
      properties:
        gene-letterbox:
          type: object
    BrowserLocale:
      type: object
      properties:
        start:
          type: integer
        end:
          type: integer
        id:
          type: string
        found:
          type: boolean
        stick:
          type: string
  examples:
    browser-locale-success:
      value:
        end: 33015899
        found: true
        id: 'homo_sapiens_GCA_000001405_14:gene:ENSG00000139618'
        start: 32847521
        stick: 'homo_sapiens_GCA_000001405_14:13'
    browser-data-3-spec-success:
      value:
      - - - ff
          - 'triticum_aestivum_GCA_900519105_1:chr3D'
          - R7590759
          - 'triticum_aestivum_GCA_900519105_1:gene:TraesCS3D02G273600'
          - true
        - gene-letterbox
        - - - 379535905
          - - 15
          - - 0
            - 1
            - 2
            - 1
            - 2
            - 1
            - 2
            - 1
            - 2
            - 1
            - 2
            - 1
            - 2
            - 1
            - 0
          - - 342
            - 213
          - - 306
            - 198
            - 277
            - 341
            - 282
            - 182
            - 1156
          - - 95
            - 96
            - 89
            - 90
            - 139
            - 116
          - string:
              - TraesCS3D02G273600
          - - 2
            - 0
          - - 3922
          - string:
              - 'triticum_aestivum_GCA_900519105_1:gene:TraesCS3D02G273600'
          - - 1
          - string:
              - protein coding
          - string:
              - Selected
          - string:
              - 'triticum_aestivum_GCA_900519105_1:transcript:TraesCS3D02G273600'
          - string:
              - TraesCS3D02G273600
          - string:
              - TraesCS3D02G273600
          - string:
              - TCTTTCTCCTTGCGATACTTCATCTGCAGCGGCTGCAGCTTGTCTCTCAG
          - - 379537950
        - R7
 