bytecodes:
    framework: |
        ; *** FIXED TEXTS ***
        const #20, "Lato"
        const #21, [12,0,199,208,213,255,255,255]
        const #10, "bp"
        const #11, [2]
        text #12, #20, #21, #10, #11
        ; *** bp top ***
        const #5, [3,0,1,1,1,1,2,0,1,0,0]
        const #6, [34]
        const #7, [10]
        const #8, [0]
        get #8, #12, #8
        const #18, [0]
        shape #5, #6, #18, #7, #18, #8
        ; *** bp bottom ***
        const #5, [3,0,1,1,2,1,2,0,1,0,0]
        shape #5, #6, #8, #7, #8, #8
        ; *** horiz lines top ***
        const #5, [0,1,1,2,1,1,2,0,2,0,0]
        const #6, [0,0]
        const #7, [0,0]
        const #8, [17,0]
        const #9, [1,1]
        const #10, [199,208,213]
        shape #5, #6, #7, #8, #9, #10
        ; *** horiz lines bottom ***
        const #5, [0,1,1,2,2,2,0,0,0,0,0]
        shape #5, #6, #7, #8, #9, #10
        ; *** left/right blanking ***
        const #5, [0,1,1,1,1,2,2,0,2,0,1]
        const #6, [0]
        const #7, [36]
        const #8, [16]
        const #9, [0]
        const #10, [255,255,255]
        shape #5, #6, #7, #8, #9, #10
        const #5, [0,1,2,2,1,2,2,0,2,0,1]
        shape #5, #6, #7, #8, #9, #10
        ; *** top/bottom blanking ***
        const #5, [0,1,1,2,1,1,2,0,2,0,2]
        const #6, [0]
        const #7, [0]
        const #8, [0]
        const #9, [17]
        const #10, [255,255,255]
        shape #5, #6, #7, #8, #9, #10
        const #5, [0,1,1,2,2,2,2,0,2,0,2]
        shape #5, #6, #7, #8, #9, #10
        ; *** corner blanking ***
        const #5, [0,1,1,1,1,1,2,0,2,0,0]
        const #6, [0]
        const #7, [36]
        const #8, [1]
        const #9, [15]
        const #10, [255,255,255]
        shape #5, #6, #7, #8, #9, #10
        const #5, [0,1,1,1,2,2,2,0,2,0,0]
        shape #5, #6, #7, #8, #9, #10
        ; *** bp corner mark bottom ***
        const #6, [36]
        const #7, [1]
        const #8, [1]
        const #9, [16]
        const #11, [199,208,213]
        shape #5, #6, #7, #8, #9, #11
        ; *** and top ***
        const #5, [0,1,1,1,1,1,2,0,2,0,0]
        shape #5, #6, #7, #8, #9, #11
        ; *** RULER ***
        ; 1. call ruler
        const #5, [20,20,20,10,15,20,30]
        ruler #6, #7, #8, #9, #5
        ; 2. draw marks
        const #5, [0,1,0,0,1,1,2,0,2,0,0]
        const #12, [1]
        const #13, [0]
        const #14, [17]
        shape #5, #6, #12, #13, #14, #11
        const #5, [0,1,0,0,2,2,2,0,2,0,0]
        shape #5, #6, #12, #13, #14, #11
        ; 3. draw text
        const #12, "Lato"
        const #13, [12,0,192,192,192,255,255,255]
        text #10, #12, #13, #9, #8
        const #5, [3,0,0,1,1,1,2,0,2,0,0]
        const #14, [0]
        const #15, [17]
        shape #5, #6, #14, #15, #14, #10
        const #5, [3,0,0,1,2,1,2,0,2,0,0]
        const #15, [1]
        shape #5, #6, #14, #15, #14, #10
        ; *** LHS ***
        allplots #41,#42,#43,#44
        const #20, "Lato"
        const #21, [12,1,96,96,96,255,255,255]
        text #12, #20, #21, #44, #43
        const #45, [0.5]
        mul #42, #42, #45
        add #41, #41, #42
        const #5, [3,0,1,1,0,1,2,10,1,0,0]
        length #45, #41
        const #6, [12]
        runsof #6, #45, #6
        const #7, [2]
        const #8, [30]
        shape #5, #6, #8, #41, #7, #12
        ; *** swatch *** XXX always first track ATM
        const #5, [0,1,1,1,0,0,2,0,2,0,0]
        const #7, [6]
        allplots #41, #42, #43, #44
        const #6, [1]
        get #41, #41, #6
        get #42, #42, #6
        const #49, [0.1]
        mul #43, #42, #49
        add #43, #43, #41
        move #44, #42
        const #49, [0.8]
        mul #44, #44, #49
        const #45, [78,168,252]
        const #6, [0]
        shape #5, #6, #7, #43, #44, #45

    contig: |
        plot #62, #0
        const #63, [1]
        get #61, #62, #63
        const #60, [0.5]
        mul #61, #61, #60
        const #63, [0]
        get #60, #62, #63
        add #60, #60, #61
        const #62, [-3]
        add #4, #60, #62
        const #5, [6]
        const #6, [192,192,192,128,128,128]
        const #7, [3]
        pick #6, #3, #6, #7
        const #10, [1,1]
        shape #10, #1, #2, #4, #5, #6

    transcript: |
        plot #62, #0
        const #63, [1]
        get #61, #62, #63
        const #60, [0.5]
        mul #61, #61, #60
        const #63, [0]
        get #60, #62, #63
        add #60, #60, #61
        const #62, [0]
        add #60, #60, #62
        ; y-position
        runsof #10, #2, #1
        merge #11, #3, #4, #5, #6
        accn #12, #11, #2
        add #13, #10, #12
        const #14, [-1]
        mul #14, #11, #14
        add #14, #13, #14
        ; extract + draw
        ; *** utr ***
        const #10, [2,1]
        move #12, #60
        const #17, [-4]
        add #12, #12, #17
        const #13, [7]
        const #15, [75,168,252]
        const #16, [0]
        eq #16, #3, #16
        move #7, #14
        const #17, [1]
        elide #7, #16, #17
        move #8, #11
        elide #8, #16, #17
        shape #10, #7, #8, #12, #13, #15
        ; *** exon ***
        const #10, [1,1]
        const #16, [1]
        eq #16, #3, #16
        move #7, #14
        const #17, [1]
        elide #7, #16, #17
        move #8, #11
        elide #8, #16, #17
        shape #10, #7, #8, #12, #13, #15
        ; *** intron ***
        const #10, [1,1]
        const #16, [2]
        move #12, #60
        const #17, [-1]
        add #12, #12, #17
        const #13, [1]
        eq #16, #3, #16
        move #7, #14
        const #17, [1]
        elide #7, #16, #17
        move #8, #11
        elide #8, #16, #17
        shape #10, #7, #8, #12, #13, #15

endpoints:
    contig-normal:
        endpoint: data/contig-normal
        bytecode: contig

    contig-shimmer:
        endpoint: data/contig-shimmer
        bytecode: contig

    trans-pc-fwd:
        endpoint: data/transcript?type=pc&dir=fwd
        bytecode: transcript

    trans-pc-rev:
        endpoint: data/transcript?type=pc&dir=rev
        bytecode: transcript

    trans-other-fwd:
        endpoint: data/transcript?type=other&dir=fwd
        bytecode: transcript

    trans-other-rev:
        endpoint: data/transcript?type=other&dir=rev
        bytecode: transcript

    framework:
        bytecode: framework

tracks:
    "internal:debug:contig":
        AI:
            endpoint: contig-shimmer
        JO:
            endpoint: contig-normal

    "internal:debug:zzz-framework":
        AZ:
            endpoint: framework

    "internal:debug:gene-pc-fwd":
        IO:
            endpoint: trans-pc-fwd

    "internal:debug:gene-pc-rev":
        IO:
            endpoint: trans-pc-rev

    "internal:debug:gene-other-fwd":
        IO:
            endpoint: trans-other-fwd

    "internal:debug:gene-other-rev":
        IO:
            endpoint: trans-other-rev
