endpoints: endpoints.yaml

api:
    1: api/1/api.yaml
    2: api/2/api.yaml
    3: api/3/api.yaml

debug-url: ./debug
jumper-url: ./locale

tracks:
    contig:
        wire: cc
        letter: G
        position: 3
        parts:
            - label

    zzz-framework:
        wire: zz
        position: -1
        parts:
            - lhs

    gene-feat:
        wire: ff
        letter: G
        position: 0
        parts:
            - label
            - names

    gene-pc-fwd:
        wire: pf
        letter: G
        position: 1
        parts:
            - label
            - names

    gene-pc-rev:
        wire: pr
        letter: G
        position: 4
        parts:
            - label
            - names

    gene-other-fwd:
        wire: of
        letter: G
        position: 2
        parts:
            - label
            - names

    gene-other-rev:
        wire: or
        letter: G
        position: 5
        parts:
            - label
            - names

    variant:
        wire: vv
        letter: V
        position: 6
        parts:
            - label

    gc:
        wire: gc
        letter: G
        position: 7
        parts:
            - label

assets:
    chevron-left:
        filter: png
        filename: chevron-left.png

    chevron-right:
        filter: png
        filename: chevron-right.png
 
    dotted-line:
        filter: png
        filename: dotted-line.png
