mod assignregs;
mod call;
mod codegen;
mod cow;
mod dealias;
mod gencontext;
mod instruction;
mod linearize;
mod prune;
mod reusedead;
mod runnums;
mod simplify;

pub use self::assignregs::assign_regs;
pub use self::call::call;
pub use self::cow::copy_on_write;
pub use self::dealias::remove_aliases;
pub use self::gencontext::GenContext;
pub use self::codegen::generate_code;
pub use self::instruction::{ Instruction, InstructionType };
pub use self::linearize::linearize;
pub use self::prune::prune;
pub use self::reusedead::reuse_dead;
pub use self::runnums::run_nums;
pub use self::simplify::simplify;
